mod commands;
mod domain;
mod error;
mod io_utils;
mod services;

use commands::{
    candidates::{extract_resume_candidates, list_story_candidates, set_story_candidate_status},
    capture::{
        classify_capture_source, create_capture_source, get_capture_source,
        list_unclassified_captures,
    },
    development::{
        create_story_from_seed_development, start_story_seed_development,
        submit_story_seed_development_response,
    },
    feedback::{get_feedback_snapshot, mark_post_published, record_post_performance},
    inspirations::{
        add_inspiration_relationship, create_inspiration_from_source, get_inspiration,
        list_inspiration_link_targets, list_inspirations, remove_inspiration_relationship,
        update_inspiration,
    },
    interviews::{
        list_guided_interviews, resume_guided_interview, start_guided_interview,
        submit_guided_interview_response,
    },
    performance::get_performance_snapshot,
    posts::{
        append_post_revision, approve_post_revision, create_post, generate_post_from_topic,
        get_post_lineage, link_post_supporting_material, list_posts,
    },
    preferences::{
        clear_last_vault, get_default_vault_root, get_last_import_directory, get_last_vault_path,
        remember_last_import_file, remember_last_vault,
    },
    privacy::{
        list_entity_reviews, resolve_entity_review, transform_confidentiality_for_public_use,
    },
    providers::{
        analyze_voice_evidence, create_manual_workspace, get_provider_settings,
        list_provider_models, test_provider_connection, update_provider_settings,
    },
    quality::lint_draft,
    roles::list_roles,
    stories::{import_story_response, list_stories, set_story_status},
    target_contexts::{
        add_target_context_relationship, create_target_context_from_source,
        extract_target_context_signals, get_target_context, list_target_context_link_targets,
        list_target_contexts, remove_target_context_relationship, update_target_context,
    },
    topics::{
        add_topic_relationship, create_theme, create_topic, get_theme, get_topic, list_themes,
        list_topic_link_targets, list_topics, remove_topic_relationship, update_theme,
        update_topic,
    },
    vault::{
        create_default_vault, create_vault, create_vault_in_parent, import_source, list_sources,
        open_vault, update_cloud_identifier_mode,
    },
    voice::{
        activate_core_voice, analyze_edit_learning, create_core_voice, create_tone_mode,
        create_voice_direction, create_voice_evidence_from_source, create_writing_rule,
        decide_edit_learning_proposal, delete_core_voice_trait, get_voice_evidence,
        list_core_voices, list_edit_learning_decisions, list_tone_modes, list_voice_directions,
        list_voice_evidence, list_voice_source_candidates, list_writing_rules,
        review_voice_evidence, save_core_voice_trait, set_voice_direction_status, update_tone_mode,
        update_writing_rule,
    },
};

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(tauri::generate_handler![
            create_vault,
            create_vault_in_parent,
            create_default_vault,
            create_capture_source,
            get_capture_source,
            list_unclassified_captures,
            classify_capture_source,
            start_story_seed_development,
            submit_story_seed_development_response,
            create_story_from_seed_development,
            create_inspiration_from_source,
            get_inspiration,
            list_inspirations,
            update_inspiration,
            add_inspiration_relationship,
            remove_inspiration_relationship,
            list_inspiration_link_targets,
            create_target_context_from_source,
            get_target_context,
            list_target_contexts,
            update_target_context,
            extract_target_context_signals,
            add_target_context_relationship,
            remove_target_context_relationship,
            list_target_context_link_targets,
            analyze_edit_learning,
            decide_edit_learning_proposal,
            list_edit_learning_decisions,
            list_voice_source_candidates,
            create_voice_evidence_from_source,
            get_voice_evidence,
            list_voice_evidence,
            review_voice_evidence,
            list_core_voices,
            create_core_voice,
            save_core_voice_trait,
            delete_core_voice_trait,
            activate_core_voice,
            list_tone_modes,
            create_tone_mode,
            update_tone_mode,
            list_voice_directions,
            create_voice_direction,
            set_voice_direction_status,
            list_writing_rules,
            create_writing_rule,
            update_writing_rule,
            create_topic,
            get_topic,
            list_topics,
            update_topic,
            create_theme,
            get_theme,
            list_themes,
            update_theme,
            add_topic_relationship,
            remove_topic_relationship,
            list_topic_link_targets,
            create_post,
            list_posts,
            generate_post_from_topic,
            append_post_revision,
            approve_post_revision,
            get_post_lineage,
            link_post_supporting_material,
            mark_post_published,
            record_post_performance,
            get_feedback_snapshot,
            open_vault,
            import_source,
            list_sources,
            update_cloud_identifier_mode,
            get_last_vault_path,
            remember_last_vault,
            clear_last_vault,
            get_last_import_directory,
            remember_last_import_file,
            get_default_vault_root,
            list_entity_reviews,
            resolve_entity_review,
            transform_confidentiality_for_public_use,
            extract_resume_candidates,
            list_story_candidates,
            set_story_candidate_status,
            start_guided_interview,
            list_guided_interviews,
            submit_guided_interview_response,
            resume_guided_interview,
            get_performance_snapshot,
            create_manual_workspace,
            get_provider_settings,
            update_provider_settings,
            list_provider_models,
            test_provider_connection,
            analyze_voice_evidence,
            lint_draft,
            list_roles,
            import_story_response,
            list_stories,
            set_story_status
        ])
        .run(tauri::generate_context!())
        .expect("error while running WorkLore");
}
